import type { Metadata } from 'next';
import './globals.css';
import LayoutProvider from '@/components/LayoutProvider';
import ZustandInitializer from './referrer';

export const metadata: Metadata = {
  title: 'Kalibrasi Kontrol & NCR',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LayoutProvider>
      <html lang="en">
        <body>
          <ZustandInitializer />
          {children}
        </body>
      </html>
    </LayoutProvider>
  );
}
